### ISSUE TITLE
[Question] Documented support for AOT platforms

### ISSUE THREAD

**Issue by LuiCat** [WattleScript/wattlescript#62]
Hi, I'm glad to know about this awesome project that inherits from moonsharp and pushes GC management further.

This is purely to confirm on the domain of features that is supported or planned -- do you consider support for AOT platforms (Xamarin or Unity3D on IOS for example) as in your list of features? Generally, integration support can be done in a separate project, however the guarantee of at least partial support of AOT platforms (I see the source generator, but not seeing direct mentioning of AOT) would be super cool 😎

Do we have any info on this that you can share here?

**Comment by CallumDev** [comment]
Hello!

AOT is definitely a supported target for WattleScript, and as far as I know there is already someone using it in Unity. The workflow should be similar to MoonSharp, with the new requirement that you need a Unity version that supports the .NET Standard 2.0 feature set.

If something about WattleScript fails to work with Unity or AOT, please reach out! Documentation will come when I have the bandwidth to download Unity and see how the MSBuild/C# source support has progressed since 2016

**Comment by LuiCat** [comment]
Thanks for your confirmation!
